import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Student } from '@/types';
import { rankStudents } from '@/utils/scoring';

export function exportResultsToPDF(students: Student[], batchName?: string) {
  const doc = new jsPDF();
  const ranked = rankStudents(students);
  const date = new Date().toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Header
  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, 210, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Typing Competition Results', 105, 18, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(batchName ? `Batch: ${batchName}` : 'All Batches', 105, 28, { align: 'center' });

  // Date
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(10);
  doc.text(`Generated on: ${date}`, 14, 45);

  // Summary Stats
  const totalStudents = ranked.length;
  const avgWpm = totalStudents > 0 
    ? Math.round(ranked.reduce((sum, s) => sum + s.wpm, 0) / totalStudents) 
    : 0;
  const avgAccuracy = totalStudents > 0 
    ? Math.round(ranked.reduce((sum, s) => sum + s.accuracy, 0) / totalStudents) 
    : 0;
  const topScore = ranked[0]?.finalScore || 0;

  doc.setFillColor(245, 247, 250);
  doc.roundedRect(14, 50, 182, 18, 3, 3, 'F');

  doc.setTextColor(60, 60, 60);
  doc.setFontSize(9);
  doc.text(`Total Students: ${totalStudents}`, 24, 60);
  doc.text(`Avg WPM: ${avgWpm}`, 70, 60);
  doc.text(`Avg Accuracy: ${avgAccuracy}%`, 115, 60);
  doc.text(`Top Score: ${topScore}`, 165, 60);

  // Top 3 Winners Section
  if (ranked.length >= 1) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175);
    doc.text('🏆 Top Performers', 14, 80);

    const top3 = ranked.slice(0, 3);
    const medals = ['🥇', '🥈', '🥉'];
    
    let yPos = 88;
    top3.forEach((student, i) => {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40, 40, 40);
      doc.text(`${medals[i]} ${student.name}`, 20, yPos);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(`Score: ${student.finalScore} | WPM: ${student.wpm} | Accuracy: ${student.accuracy}%`, 60, yPos);
      yPos += 8;
    });
  }

  // Results Table
  const tableStartY = ranked.length >= 3 ? 115 : 80;

  autoTable(doc, {
    startY: tableStartY,
    head: [['Rank', 'Name', 'Batch', 'WPM', 'Accuracy', 'Errors', 'Final Score']],
    body: ranked.map((student) => [
      student.rank?.toString() || '-',
      student.name,
      student.batch,
      student.wpm.toString(),
      `${student.accuracy}%`,
      student.errors.toString(),
      student.finalScore.toString(),
    ]),
    theme: 'striped',
    headStyles: {
      fillColor: [30, 64, 175],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center',
    },
    bodyStyles: {
      halign: 'center',
    },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { halign: 'left', cellWidth: 40 },
      2: { cellWidth: 30 },
      3: { cellWidth: 20 },
      4: { cellWidth: 25 },
      5: { cellWidth: 20 },
      6: { cellWidth: 30, fontStyle: 'bold' },
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Typing Competition Manager', 105, pageHeight - 10, { align: 'center' });

  // Save
  const filename = batchName 
    ? `typing-results-${batchName.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`
    : `typing-results-all-${Date.now()}.pdf`;
  
  doc.save(filename);
}
